<?xml version="1.0" encoding="utf-8"?>
<!--
	Filename: template.xml
	Author: Connor Marsden
	Creation date: 09/09/2020
-->

<!DOCTYPE goHoliday
  [
    
    <!ELEMENT goHoliday (package*)>
    <!ELEMENT package (packageName, description, cost, nightNo, popularity, accommodationOptions+, couponCode?, reviews*, filenamePic+, promoURL+, availability, specialEvent*, xmlImage*)>
    <!ELEMENT packageName (#PCDATA)>
    <!ELEMENT description (#PCDATA)>
    <!ELEMENT cost (#PCDATA)>
    <!ELEMENT nightNo (#PCDATA)>
    <!ELEMENT popularity (#PCDATA)>
    <!ELEMENT accommodationOptions ((location, additionalCost))>
    <!ELEMENT location (#PCDATA)>
    <!ELEMENT additionalCost (#PCDATA)>
    <!ELEMENT couponCode (#PCDATA)>
    <!ELEMENT reviews (#PCDATA)>
    <!ELEMENT filenamePic (#PCDATA)>
    <!ELEMENT promoURL (#PCDATA)>
    <!ELEMENT availability (#PCDATA)>
    <!ELEMENT specialEvent (#PCDATA)>
    <!ELEMENT xmlImage (#PCDATA)>


  ]>


<goHoliday>
  <package>
    <packageName></packageName>
    <description></description>
    <cost></cost>
    <nightNo></nightNo>
    <popularity></popularity>
    <accommodationOptions>
      <location></location>
      <additionalCost></additionalCost>
    </accommodationOptions>
    <couponCode></couponCode>
    <reviews></reviews>
    <filenamePic></filenamePic>
    <promoURL></promoURL>
    <availability></availability>
    <specialEvent></specialEvent>
    <xmlImage></xmlImage>
  </package>
</goHoliday>
